schema_version = "1.0.0"

id = "quick_infill"
version = "1.0.0"
name = "Quick Infill"
tagline = "Fixes resin trapping cavities"
maintainer = "Alex Bannwarth"
type = "add-on"

blender_version_min = "4.5.0"

license = ["SPDX:GPL-2.0-or-later"]

wheels = [
    "./wheels/meshlib-3.0.7.226-py38.py39.py310.py311.py312.py313-none-win_amd64.whl",
    "./wheels/numpy-2.3.3-cp311-cp311-win_amd64.whl"
]

copyright = [
    "2025 Alex Bannwarth",
    "2025 Printable Scenery"
]

