schema_version = "1.0.0"
id = "quick_infill"
version = "1.0.8"
name = "Quick Infill"
tagline = "Fixes resin trapping cavities"
maintainer = "Alex Bannwarth"
type = "add-on"
blender_version_min = "5.2.0"
license = [ "SPDX:GPL-2.0-or-later",]
wheels = [ "./wheels/meshlib_core-3.1.4.297-py38.py39.py310.py311.py312.py313.py314-none-win_amd64.whl", "./wheels/meshlib-3.1.4.297-py38.py39.py310.py311.py312.py313.py314-none-win_amd64.whl", "./wheels/numpy-2.5.3-cp313-cp313-win_amd64.whl",]
copyright = [ "2025 Alex Bannwarth", "2025 Printable Scenery",]
